name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: echo CI DONE

      # 1. AWS 계정 세팅하기.
      - name: AWS Setting
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 2. AWS S3 버킷에 업로드하기.
      - name: Upload to S3 Bucket
        run: aws deploy push --application-name code-deploy --description "practice cicd" --s3-location s3://practice-cicd/server/build.zip --source .

      - name: Code Deploy
        run: aws deploy create-deployment --application-name jojoldu-deploy-app --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name jojoldu --s3-location bucket=practice-cicd,bundleType=zip,key=server/build.zip